"""Derive the numerical results note from computed tables, preserving units."""

import json
import numpy as np
import pandas as pd
from scipy.stats import t


def md_table(df):
    headers = list(df.columns)
    rows = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join(["---"] * len(headers)) + " |",
    ]
    rows.extend(
        "| " + " | ".join(map(str, row)) + " |"
        for row in df.itertuples(index=False, name=None)
    )
    return "\n".join(rows)


def build(root):
    out = root / "results/tables"
    summary = json.loads((root / "results/summary.json").read_text())
    itt = pd.read_csv(out / "itt.csv")
    itt = itt[itt.group == "All"].copy()
    itable = pd.DataFrame(
        {
            "Outcome": itt.metric,
            "Control (%)": itt.control.map(lambda v: f"{v*100:.3f}"),
            "Treatment (%)": itt.treatment.map(lambda v: f"{v*100:.3f}"),
            "ITT (pp)": itt.effect.map(lambda v: f"{v*100:+.3f}"),
            "95% CI (pp)": [
                f"[{lo*100:+.3f}, {hi*100:+.3f}]"
                for lo, hi in zip(itt.lower, itt.upper)
            ],
        }
    )
    pc = pd.read_csv(out / "policy_comparisons.csv")
    ptable = pd.DataFrame(
        {
            "Scenario": pc.scenario,
            "Policy": pc.policy,
            "Value vs fixed 50% ($K)": pc["mean"].map(lambda v: f"{v/1000:+.1f}"),
            "95% paired CI ($K)": [
                f"[{lo/1000:+.1f}, {hi/1000:+.1f}]"
                for lo, hi in zip(pc.lower, pc.upper)
            ],
        }
    )
    fac = pd.read_csv(out / "factorial.csv").pivot(
        index="seed", columns="intervention", values="value"
    )
    interaction = fac.Interaction
    half = (
        t.ppf(0.975, len(interaction) - 1)
        * interaction.std()
        / np.sqrt(len(interaction))
    )
    seq = pd.read_csv(out / "sequential_validation.csv")
    seq = (
        seq.assign(error=seq.estimate - seq.truth)
        .groupby("policy")
        .agg(
            bias=("error", "mean"),
            coverage=("covered", "mean"),
            effective=("effective_sample", "mean"),
        )
    )
    stable = pd.DataFrame(
        {
            "Policy": seq.index,
            "Bias": seq.bias.map(lambda v: f"{v:+.3f}"),
            "Coverage": seq.coverage.map(lambda v: f"{v:.1%}"),
            "Mean effective trajectories": seq.effective.map(lambda v: f"{v:.1f}"),
        }
    )
    mc = summary["itt_validation"]
    models = pd.read_csv(out / "models.csv")[
        ["model", "population", "roc_auc", "pr_auc", "brier"]
    ]
    for col in ["roc_auc", "pr_auc", "brier"]:
        models[col] = models[col].map(lambda v: f"{v:.3f}")
    merchant = pd.read_csv(out / "merchant.csv")[
        ["merchant", "raw_relative", "standardized_relative"]
    ]
    for col in ["raw_relative", "standardized_relative"]:
        merchant[col] = merchant[col].map(lambda v: f"{v:.3f}")
    text = f"""# Computed results and uncertainty

Generated by `run_all.py` from the committed configuration and analysis functions. Supplied case point estimates remain in `data/case_inputs/`; all results below belong to the executable reconstruction.

## Randomized intervention

{md_table(itable)}

Loss rates use attempted value; completion uses attempted transaction count. These generated magnitudes differ from the supplied experiment by design. Across {mc['repetitions']} fresh stratified assignments, net-ratio ITT bias is **{mc['bias']*100:+.4f} percentage points**, empirical 95% interval coverage is **{mc['coverage']:.1%}**, and the Monte Carlo standard error of that coverage is **{mc['coverage_mc_se']:.2%}**. The finite-population truth is computed from both potential outcomes; estimation uses only observed outcomes. See `heterogeneity.csv` for the missing-minus-present treatment-effect contrast.

## Merchant comparison

{md_table(merchant)}

The generated measure is fraud incidence standardized to a common pre-routing geography/CNP mix. Merchant B's excess largely follows composition. Merchant A retains the route-linked mechanism. The source case uses richer matching and loss-rate outcomes, so its 2.8×/1.6× values belong to a separate analysis.

## Temporal information diagnostics

{md_table(models)}

`pr_auc` is average precision. The specialized model has the additional PSP feature and trains on the early weak-observability subset. Masked-high and natural-low diagnostics fit separately on the same remaining columns. Point estimates are descriptive; the calibration plot and `calibration.csv` expose probability performance.

![Calibration on the generated temporal holdout](../results/figures/12_calibration.svg)

## Policy value across assumptions

{md_table(ptable)}

Each comparison uses 12 paired seeds over 84 days. Intervals represent Monte Carlo uncertainty conditional on a specified generator. The high-friction stress scenario raises legitimate contribution margin from $0.65 to $65 per completed attempt, deliberately testing a high-value transaction setting. Low arrivals use 1,100 cases/week; high displacement uses strength 0.95. These scenario changes are explicit assumptions, not estimates from the case.

Default adaptive and delayed rules remain at 80% throughout and match fixed high intensity. At lower arrivals, the controller releases authentication and sacrifices loss-prevention value under the specified thresholds. High friction can change which fixed intensity is economically attractive. These results make threshold selection and cost calibration part of the decision.

## Operational interaction

The equal-dose factorial interaction averages **${interaction.mean()/1000:+.1f}K**, with a paired-seed 95% interval of **[${(interaction.mean()-half)/1000:+.1f}K, ${(interaction.mean()+half)/1000:+.1f}K]**. Its sign is retained from the simulation. The combined intervention's gain over either component and superadditivity are different comparisons.

![Equal-dose operational interventions](../results/figures/11_operations_factorial.svg)

`uncongested_ablation.csv` removes the service-capacity constraint while retaining evidence delays, deadlines and recovery quality. Under that ablation, adding capacity changes cost alone, verified in the test suite.

## Sequential-policy estimator validation

{md_table(stable)}

For each rule, 60 independently randomized datasets contain 2,200 four-step trajectories. Compatible histories receive weight 16; the average effective sample is therefore much smaller than the number of episodes. A separate 100,000-trajectory on-policy simulation approximates the true expectation. Coverage's Monte Carlo standard error is roughly three percentage points at the reported values; 60 repetitions give a diagnostic rather than a precise calibration certificate. The adaptive estimate's finite Monte Carlo bias is reported directly.

The operational simulator and this sequential validation use different data-generating processes. Forward queue-policy comparisons validate operational consequences under assumptions; the sequential demonstration checks identification and weighting under randomized history support.

## Reproducibility record

Python {summary['python']}; direct package versions are in `results/summary.json` and `requirements-lock.txt`. All point estimates, scenario comparisons, validation replicates, case inputs and source fingerprints are committed or reproducible from the entry point. Supplied-aggregate experimental uncertainty remains unavailable from the original materials.
"""
    (root / "docs/results.md").write_text(text)
